name: CloudFoundry - Build, Deploy and Test

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Log Event Data
        run: echo '${{ toJson(github.event) }}'
